--Se eliminan catalogos de script inicial, se actualiza informacion con catalogos a nivel nacional.

UPDATE motor_interprete.cat_dependencia SET activo = false;

--Se agregan elementos de dependencias federales

INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (111,'Autoridad Educativa Federal en la Ciudad de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (112,'Agencia Espacial Mexicana',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (113,'Agencia Federal de Aviación Civil',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (114,'Archivo General de la Nación',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (115,'Agroasemex S.A.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (116,'Aeropuerto Internacional de la Ciudad de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (117,'Aeropuerto Internacional Felipe Ángeles, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (118,'Agencia Nacional de Aduanas de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (119,'Agencia Reguladora de Transporte Ferroviario',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (120,'Aeropuertos y Servicios Auxiliares',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (121,'Agencia de Seguridad, Energía y Ambiente',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (122,'Administración del Sistema Portuario Nacional Acapulco, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (123,'Administración del Sistema Portuario Nacional Altamira, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (124,'Administración del Sistema Portuario Nacional Coatzacoalcos, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (125,'Administración del Sistema Portuario Nacional Cabo San Lucas, S.A. de C.V. ',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (126,'Administración del Sistema Portuario Nacional Dos Bocas, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (127,'Administración del Sistema Portuario Nacional Ensenada, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (128,'Administración del Sistema Portuario Nacional Guaymas, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (129,'Administración del Sistema Portuario Nacional Lázaro Cárdenas, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (130,'Administración del Sistema Portuario Nacional Manzanillo, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (131,'Administración del Sistema Portuario Nacional Mazatlán, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (132,'Administración del Sistema Portuario Nacional Puerto Chiapas, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (133,'Administración del Sistema Portuario Nacional Progreso, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (134,' Administración del Sistema Portuario Nacional Salina Cruz, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (135,'Administración del Sistema Portuario Nacional Tampico, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (136,'Administración del Sistema Portuario Nacional Topolobampo, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (137,'Administración del Sistema Portuario Nacional Tuxpan, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (138,'Administración del Sistema Portuario Nacional Puerto Vallarta, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (139,'Administración del Sistema Portuario Nacional Veracruz, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (140,'Banco del Bienestar, S.N.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (141,'Banco Nacional de Comercio Exterior, S.N.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (142,'Banco Nacional del Ejército, Fuerza Aérea y Armada, S.N.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (143,'Banco Nacional de Obras y Servicios Públicos, S.N.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (144,'Secretaría de Bienestar',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (145,'Laboratorios de Biológicos y Reactivos de México, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (146,'Canal ONCE',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (147,'Caminos y Puentes Federales de Ingresos y Servicios Conexos',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (148,'Centro de Capacitación Cinematográfica, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (149,'Comisión Ejecutiva de Atención a Víctimas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (150,'Compañía Operadora del Centro Cultural y Turístico de Tijuana, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (151,'Centro Nacional de Control de Energía',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (152,'Centro Nacional de Control del Gas Natural',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (153,'Centro Nacional de Metrología',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (154,'Centro de Enseñanza Técnica Industrial',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (155,'Centro Federal De Conciliación Y Registro Laboral',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (156,'Centro Geo',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (157,'Centro de Investigación en Alimentación y Desarrollo, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (158,'CIATEC, A.C. “Centro de Innovación Aplicada en Tecnologías Competitivas”',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (159,'Centro de Investigación y Asistencia en Tecnología y Diseño del Estado de Jalisco, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (160,'CIATEQ, A.C. Centro de Tecnología Avanzada',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (161,'Centro de Investigaciones Biológicas del Noroeste, S.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (162,'Centro de Investigación Científica y de Educación Superior de Ensenada',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (163,'Centro de Investigación Científica de Yucatán, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (164,'Centro de Investigación y Docencia Económicas, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (165,'Centro de Ingeniería y Desarrollo Industrial',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (166,'Centro de Investigación y Desarrollo Tecnológico en Electroquímica',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (167,'Centro de Investigaciones y Estudios Superiores en Antropología Social',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (168,'Corredor Interoceánico del Istmo de Tehuantepec',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (169,'Centros de Integración Juvenil, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (170,'Centro de Investigación en Matemáticas A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (171,'Centro de Investigación en Materiales Avanzados, S.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (172,'Cineteca Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (173,'Centro de Investigación y de Estudios Avanzados del Instituto Politécnico Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (174,'Centro de Investigaciones en Optica, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (175,'Centro de Investigación en Química Aplicada',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (176,'Consejería Jurídica del Ejecutivo Federal',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (177,'Casa de Moneda de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (178,'Coordinación Nacional de Becas para el Bienestar Benito Juárez',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (179,'Comisión Nacional Bancaria y de Valores',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (180,'Comisión Nacional de Hidrocarburos',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (181,'Comisión Nacional de Seguros y Fianzas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (182,'Comisión Nacional de Seguridad Nuclear y Salvaguardias',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (183,'Comisión de Operación y Fomento de Actividades Académicas del Instituto Politécnico Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (184,'Comisión Federal para la Protección Contra Riesgos Sanitarios',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (185,'Colegio de Bachilleres',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (186,'El Colegio de la Frontera Norte, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (187,'El Colegio de Michoacán, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (188,'Colegio de Postgraduados',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (189,'El Colegio de San Luis',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (190,'Compañía Mexicana de Exploraciones, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (191,'Corporación Mexicana de Investigación en Materiales, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (192,'Comisión Nacional de Cultura Física y Deporte',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (193,'Comité Nacional para el Desarrollo Sustentable de la Caña de Azúcar',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (194,'Consejo Nacional para el Desarrollo y la Inclusión de las Personas con Discapacidad',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (195,'Consejo Nacional de Fomento Educativo',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (196,'Comisión Nacional Forestal',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (197,'Comisión Nacional del Agua',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (198,'Consejo Nacional de Humanidades Ciencias y Tecnologías',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (199,'Colegio Nacional de Educación Profesional Técnica',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (200,'Comisión Nacional de los Libros de Texto Gratuitos',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (201,'Comisión Nacional de Mejora Regulatoria',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (202,'Comisión Nacional de Áreas Naturales Protegidas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (203,'Comisión Nacional de Acuacultura y Pesca',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (204,'Consejo Nacional para Prevenir la Discriminación',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (205,'Comisión Nacional de los Salarios Mínimos',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (206,'Comisión Nacional de Vivienda',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (207,'Comisión Nacional de las Zonas Aridas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (208,'Comisión Nacional para la Protección y Defensa de los Usuarios de Servicios Financieros',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (209,'Consejo Nacional de Evaluación de la Política de Desarrollo Social',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (210,'Consejo Nacional de Normalización y Certificación de Competencias Laborales',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (211,'Comisión Nacional del Sistema de Ahorro para el Retiro',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (212,'Comisión Nacional para el Uso Eficiente de la Energía',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (213,'Comisión Reguladora de Energía',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (214,'Colegio Superior Agropecuario del Estado de Guerrero',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (215,'Secretaría de Cultura',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (216,'Diconsa, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (217,'Estudios Churubusco Azteca, S.A.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (218,'El Colegio de la Frontera Sur',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (219,'Educal, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (220,'Exportadora de Sal, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (221,'Fondo de Cultura Economica',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (222,'Ferrocarril del Istmo de Tehuantepec, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (223,'Fideicomiso de Formación y Capacitación para el Personal de la Marina Mercante Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (224,'Fideicomiso de Fomento Minero',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (225,'Fideicomiso Fondo Nacional de Fomento Ejidal',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (226,'Financiera para el Bienestar',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (227,'Financiera para el Bienestar-MEXSAT',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (228,'Fondo de Garantía y Fomento para la Agricultura, Ganadería y Avicultura',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (229,'Fideicomiso de Riesgo Compartido',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (230,'Financiera Nacional de Desarrollo Agropecuario, Rural, Forestal y Pesquero',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (231,'Fondo de Capitalización e Inversión del Sector Rural',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (232,'Fondo Nacional para el Fomento de las Artesanías',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (233,'Fondo Nacional de Fomento al Turismo',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (234,'Fondo de la Vivienda del ISSSTE',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (235,'Grupo Aeroportuario de la Ciudad de México Nuevo Aeropuerto',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (236,'Grupo Aeroportuario, Ferroviario, de Servicios Auxiliares y Conexos, Olmeca-Maya-Mexica, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (237,'Hospital General Dr. Manuel Gea González',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (238,'Guardia Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (239,'Hospital General de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (240,'Hospital Infantil de México Federico Gómez',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (241,'Hospital Juarez  de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (242,'Impresora y Encuadernadora Progreso, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (243,'Instituto Mexicano de Cinematografía',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (244,'Instituto Mexicano de la Radio',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (245,'Instituto Mexicano de Investigación de Pesca y Acuacultura Sustentables',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (246,'Instituto Mexicano de la Juventud',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (247,'Instituto de Investigaciones "Dr. José María Luis Mora',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (248,'Instituto Mexicano del Petróleo',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (249,'Instituto Mexicano de la Propiedad Industrial',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (250,'Instituto Mexicano del Seguro Social',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (251,'Servicios de Salud del Instituto Mexicano del Seguro Social para el Bienestar',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (252,'Instituto Mexicano del Transporte',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (253,'Instituto Mexicano de Tecnología del Agua',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (254,'Instituto Nacional de la Economía Social',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (255,'Instituto Nacional de Antropología e Historia',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (256,'Instituto Nacional de Lenguas Indígenas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (257,'Instituto Nacional de Astrofísica, Optica y Electrónica',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (258,'Instituto Nacional de las Personas Adultas Mayores',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (259,'Instituto Nacional de Pesca',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (260,'Instituto Nacional de Bellas Artes y Literatura',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (261,'Instituto Nacional para el Desarrollo de Capacidades del Sector Rural, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (262,'Instituto Nacional de Cancerología',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (263,'Instituto Nacional de Cardiología Ignacio Chávez',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (264,'Instituto Nacional de Ciencias Médicas y Nutrición “Salvador Zubirán”',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (265,'Instituto de Administración y Avalúos de Bienes Nacionales',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (266,'Instituto Para Devolver Al Pueblo Lo Robado',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (267,'Instituto Nacional para la Educación de los Adultos',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (268,'Instituto Nacional de Ecología y Cambio Climático',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (269,'Instituto de Ecología, A.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (270,'Instituto Nacional de Electricidad y Energías Limpias',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (271,'Instituto Nacional de Enfermedades Respiratorias',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (272,'Instituto del Fondo Nacional para el Consumo de los Trabajadores',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (273,'INFOTEC Centro De Investigación e Innovación en Tecnologías De La Información y Comunicación',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (274,'Instituto Nacional de Geriatría',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (275,'Instituto Nacional de Investigaciones Forestales, Agrícolas y Pecuarias',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (276,'Instituto Nacional de la Infraestructura Física Educativa',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (277,'Instituto Nacional de Investigaciones Nucleares',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (278,'Instituto Nacional de Migración',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (279,'Instituto Nacional de Medicina Genómica',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (280,'Instituto Nacional de las Mujeres',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (281,'Instituto Nacional de Neurología y Neurocirugía Manuel Velasco Suárez',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (282,'InnovaBienestar de México, S.A.P.I. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (283,'Instituto Nacional de Pediatría',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (284,'Instituto Nacional de Perinatología',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (285,'Instituto Nacional de los Pueblos Indígenas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (286,'Instituto Nacional de Psiquiatría Ramón de la Fuente Muñiz',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (287,'Instituto Nacional de Rehabilitación',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (288,'Instituto de Salud para el Bienestar',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (289,'Instituto Nacional de Salud Pública',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (290,'Instituto Nacional Del Suelo Sustentable',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (291,'Instituto para la Protección al Ahorro Bancario',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (292,'Instituto Potosino de Investigación Científica y Tecnológica AC',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (293,'Instituto Politécnico Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (294,'Instituto de Seguridad Social para las Fuerzas Armadas Mexicanas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (295,'Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (296,'Liconsa, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (297,'Lotería Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (298,'Comisión Nacional para la Mejora Continua de la Educación',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (299,'Nacional Financiera, S.N.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (300,'Notimex, Agencia de Noticias del Estado Mexicano',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (301,'Prevención y Readaptación Social',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (302,'Oficina de la Presidencia de la República',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (303,'Procuraduría Agraria',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (304,'Petróleos Mexicanos',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (305,'Procuraduría de la Defensa del Contribuyente',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (306,'Procuraduría Federal del Consumidor',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (307,'Procuraduría Federal de la Defensa del Trabajo',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (308,'Procuraduría Federal de Protección al Ambiente',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (309,'Organismo Promotor de Inversiones en Telecomunicaciones',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (310,'Productora Nacional de Biológicos Veterinarios',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (311,'Registro Agrario Nacional',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (312,'Secretaría de Agricultura y Desarrollo Rural',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (313,'Servicio de Administración Tributaria',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (314,'Secretaría de Economía',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (315,'Secretaría de Turismo',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (316,'Secretaría de Desarrollo Agrario Territorial y Urbano',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (317,'Seguridad Alimentaria Mexicana (SEGALMEX)',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (318,'Secretaría de Gobernación',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (319,'Secretaría del Medio Ambiente y Recursos Naturales',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (320,'Servicio Nacional de Sanidad, Inocuidad y Calidad Agroalimentaria',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (321,'Servicios a la Navegación en el Espacio Aéreo Mexicano',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (322,'Secretaría de Energía',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (323,'Secretaría de Educación Pública',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (324,'Servicio Postal Mexicano',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (325,'Secretaría Ejecutiva del Sistema Nacional Anticorrupción',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (326,'Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (327,'Secretaría de la Función Pública',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (328,'Servicio Geológico Mexicano',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (329,'Secretaría de Hacienda y Crédito Público',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (330,'Sociedad Hipotecaria Federal, S.N.C.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (331,'Servicio de Información Agroalimentaria y Pesquera',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (332,'Secretaría de Infraestructura, Comunicaciones y Transportes',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (333,'Sistema Nacional para el Desarrollo Integral de la Familia',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (334,'Servicio Nacional de Inspección y Certificación de Semillas',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (335,'Servicio de Protección Federal',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (336,'Sistema Público de Radiodifusión del Estado Mexicano',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (337,'Secretaría de Relaciones Exteriores',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (338,'Secretaría de Salud',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (339,'Secretaría de Seguridad y Protección Ciudadana',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (340,'Secretaría del Trabajo y Previsión Social',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (341,'SuperISSSTE',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (342,'Talleres Gráficos de México',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (343,'Tren Maya S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (344,'Tribunales Agrarios',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (345,'Televisión Metropolitana, S.A. de C.V.',true);
INSERT INTO motor_interprete.cat_dependencia (id_dependencia,descripcion,activo) VALUES (346,'Universidad Pedagógica Nacional',true);
