--SE MODIFICA CAMPO API_KEY PARA PERMITIR VALORES NULOS AL GUARDAR LA INFORMACION DE LA SECCION GESTION DEL TRAMITE
ALTER TABLE motor_interprete.det_gestion_usuario ALTER COLUMN api_key DROP NOT NULL;