ALTER TABLE motor_interprete.archivos_respuesta_token ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.archivos_respuesta_token ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.bit_movimientos_secciones ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.bit_movimientos_secciones ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.bit_movimientos_secciones ALTER COLUMN id_registro_movimiento TYPE int8 USING id_registro_movimiento::int8;
ALTER TABLE motor_interprete.bit_movimientos_secciones ALTER COLUMN id_registro_movimiento DROP DEFAULT;
ALTER TABLE motor_interprete.bit_movimientos_tramite ALTER COLUMN id_tramite TYPE int8 USING id_tramite::int8;
ALTER TABLE motor_interprete.bit_movimientos_tramite ALTER COLUMN id_tramite DROP DEFAULT;
ALTER TABLE motor_interprete.componente ALTER COLUMN id_subseccion_formulario TYPE int8 USING id_subseccion_formulario::int8;
ALTER TABLE motor_interprete.componente ALTER COLUMN id_subseccion_formulario DROP DEFAULT;
ALTER TABLE motor_interprete.componente_campo_texto ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_campo_texto ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_carga_documentos ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_carga_documentos ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_checkbox ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_checkbox ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_checkbox_unico ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_checkbox_unico ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_datos_domicilio ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_datos_domicilio ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_datos_personales ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_datos_personales ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_datos_personales_llave ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_datos_personales_llave ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_fecha ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_fecha ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_informativo ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_informativo ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_menu_desplegable ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_menu_desplegable ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.componente_radioboton ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.componente_radioboton ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.crc_carga_documentos_tipo_archivo ALTER COLUMN id_componente_carga TYPE int8 USING id_componente_carga::int8;
ALTER TABLE motor_interprete.crc_carga_documentos_tipo_archivo ALTER COLUMN id_componente_carga DROP DEFAULT;
ALTER TABLE motor_interprete.det_acceso_llave ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_acceso_llave ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_analytics ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_analytics ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_apoyo_otorgado ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_apoyo_otorgado ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.det_captcha ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_captcha ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_elementos_checkbox ALTER COLUMN id_componente_checkbox TYPE int8 USING id_componente_checkbox::int8;
ALTER TABLE motor_interprete.det_elementos_checkbox ALTER COLUMN id_componente_checkbox DROP DEFAULT;
ALTER TABLE motor_interprete.det_elementos_menu ALTER COLUMN id_componente_menu TYPE int8 USING id_componente_menu::int8;
ALTER TABLE motor_interprete.det_elementos_menu ALTER COLUMN id_componente_menu DROP DEFAULT;
ALTER TABLE motor_interprete.det_elementos_radioboton ALTER COLUMN id_componente_radioboton TYPE int8 USING id_componente_radioboton::int8;
ALTER TABLE motor_interprete.det_elementos_radioboton ALTER COLUMN id_componente_radioboton DROP DEFAULT;
ALTER TABLE motor_interprete.det_elementos_token ALTER COLUMN id_archivo_respuesta TYPE int8 USING id_archivo_respuesta::int8;
ALTER TABLE motor_interprete.det_elementos_token ALTER COLUMN id_archivo_respuesta DROP DEFAULT;
ALTER TABLE motor_interprete.det_elementos_token ALTER COLUMN id_componente TYPE int8 USING id_componente::int8;
ALTER TABLE motor_interprete.det_elementos_token ALTER COLUMN id_componente DROP DEFAULT;
ALTER TABLE motor_interprete.det_especificacion_requisito ALTER COLUMN id_requisito TYPE int8 USING id_requisito::int8;
ALTER TABLE motor_interprete.det_especificacion_requisito ALTER COLUMN id_requisito DROP DEFAULT;
ALTER TABLE motor_interprete.det_excepcion_tramite ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_excepcion_tramite ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.det_firma_digital ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_firma_digital ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_gestion_usuario ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_gestion_usuario ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_home ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_home ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_legales ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_legales ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_objetivos_programa ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_objetivos_programa ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.det_pago ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_pago ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_pausas_proyecto ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_pausas_proyecto ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_poblacion_objetivo ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_poblacion_objetivo ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.det_programa_social ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_programa_social ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.det_requisito ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_requisito ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.det_security_domain ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.det_security_domain ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.det_tramite_servicio ALTER COLUMN id_detalle_home TYPE int8 USING id_detalle_home::int8;
ALTER TABLE motor_interprete.det_tramite_servicio ALTER COLUMN id_detalle_home DROP DEFAULT;
ALTER TABLE motor_interprete.parametros_detalle_pago ALTER COLUMN id_detalle_pago TYPE int8 USING id_detalle_pago::int8;
ALTER TABLE motor_interprete.parametros_detalle_pago ALTER COLUMN id_detalle_pago DROP DEFAULT;
ALTER TABLE motor_interprete.secciones_formulario ALTER COLUMN id_proyecto TYPE int8 USING id_proyecto::int8;
ALTER TABLE motor_interprete.secciones_formulario ALTER COLUMN id_proyecto DROP DEFAULT;
ALTER TABLE motor_interprete.subsecciones_formulario ALTER COLUMN id_seccion_formulario TYPE int8 USING id_seccion_formulario::int8;
ALTER TABLE motor_interprete.subsecciones_formulario ALTER COLUMN id_seccion_formulario DROP DEFAULT;

-- ELIMINACIÓN DE SECUENCIAS AUTOGENERADAS
DROP SEQUENCE motor_interprete.subsecciones_formulario_id_seccion_formulario_seq;
DROP SEQUENCE motor_interprete.parametros_detalle_pago_id_detalle_pago_seq;
DROP SEQUENCE motor_interprete.det_tramite_servicio_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_security_domain_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_requisito_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_programa_social_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_poblacion_objetivo_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_pausas_proyecto_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_pago_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_objetivos_programa_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_legales_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_home_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_gestion_usuario_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_firma_digital_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_excepcion_tramite_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_especificacion_requisito_id_requisito_seq;
DROP SEQUENCE motor_interprete.det_elementos_token_id_componente_seq;
DROP SEQUENCE motor_interprete.det_elementos_token_id_archivo_respuesta_seq;
DROP SEQUENCE motor_interprete.det_elementos_radioboton_id_componente_radioboton_seq;
DROP SEQUENCE motor_interprete.det_elementos_menu_id_componente_menu_seq;
DROP SEQUENCE motor_interprete.det_elementos_checkbox_id_componente_checkbox_seq;
DROP SEQUENCE motor_interprete.det_captcha_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_apoyo_otorgado_id_detalle_home_seq;
DROP SEQUENCE motor_interprete.det_analytics_id_proyecto_seq;
DROP SEQUENCE motor_interprete.det_acceso_llave_id_proyecto_seq;
DROP SEQUENCE motor_interprete.crc_carga_documentos_tipo_archivo_id_componente_carga_seq;
DROP SEQUENCE motor_interprete.componente_radioboton_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_menu_desplegable_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_fecha_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_informativo_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_datos_personales_llave_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_datos_personales_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_datos_domicilio_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_checkbox_unico_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_checkbox_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_carga_documentos_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_campo_texto_id_componente_seq;
DROP SEQUENCE motor_interprete.componente_id_subseccion_formulario_seq;
DROP SEQUENCE motor_interprete.bit_movimientos_tramite_id_tramite_seq;
DROP SEQUENCE motor_interprete.bit_movimientos_secciones_id_proyecto_seq;
DROP SEQUENCE motor_interprete.bit_movimientos_secciones_id_registro_movimiento_seq;
DROP SEQUENCE motor_interprete.archivos_respuesta_token_id_proyecto_seq;
DROP SEQUENCE motor_interprete.secciones_formulario_id_proyecto_seq;