--SE CREA SECUENCIA PARA CONTROLAR EL CONSECUTIVO DE SOLICITUD DE LINEA DE CAPTURA
CREATE SEQUENCE motor_interprete.consecutivo_solicitud_linea_de_captura_seq
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;