package mx.gob.atdt.interprete.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CatCodigosPostales generated by hbm2java
 */
@Entity
@Table(name = "cat_codigos_postales", schema = "motor_interprete")
@NamedQueries({
	@NamedQuery(name = "CodigosPostales.buscarCodigoPostal", 
			query =" SELECT DISTINCT NEW  mx.gob.atdt.interprete.commons.dto.CatCodigosPostalesDTO " +
				" (ccp.idCodigoPostal, ccp.codigoPostal, ca.idAsentamiento, cm.idMunicipio, ce.idEstado )" +
				" FROM CatCodigosPostales ccp " +
				" INNER JOIN ccp.catEstados ce" +
				" INNER JOIN ccp.catAsentamientos ca" +
				" INNER JOIN ccp.catMunicipios cm" +
				" WHERE ccp.codigoPostal = :codigoPostal")
})
public class CatCodigosPostales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2439103959859426708L;
	
	private int idCodigoPostal;
	private CatAsentamientos catAsentamientos;
	private CatEstados catEstados;
	private CatMunicipios catMunicipios;
	private String codigoPostal;
	private int idTipoAsentamiento;

	public CatCodigosPostales() {
	}

	public CatCodigosPostales(int idCodigoPostal, CatAsentamientos catAsentamientos, CatEstados catEstados,
			CatMunicipios catMunicipios, String codigoPostal, int idTipoAsentamiento) {
		this.idCodigoPostal = idCodigoPostal;
		this.catAsentamientos = catAsentamientos;
		this.catEstados = catEstados;
		this.catMunicipios = catMunicipios;
		this.codigoPostal = codigoPostal;
		this.idTipoAsentamiento = idTipoAsentamiento;
	}

	@Id
	@Column(name = "id_codigo_postal", unique = true, nullable = false)
	public int getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(int idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asentamiento", nullable = false)
	public CatAsentamientos getCatAsentamientos() {
		return this.catAsentamientos;
	}

	public void setCatAsentamientos(CatAsentamientos catAsentamientos) {
		this.catAsentamientos = catAsentamientos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	public CatEstados getCatEstados() {
		return this.catEstados;
	}

	public void setCatEstados(CatEstados catEstados) {
		this.catEstados = catEstados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	public CatMunicipios getCatMunicipios() {
		return this.catMunicipios;
	}

	public void setCatMunicipios(CatMunicipios catMunicipios) {
		this.catMunicipios = catMunicipios;
	}

	@Column(name = "codigo_postal", nullable = false, length = 5)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "id_tipo_asentamiento", nullable = false)
	public int getIdTipoAsentamiento() {
		return this.idTipoAsentamiento;
	}

	public void setIdTipoAsentamiento(int idTipoAsentamiento) {
		this.idTipoAsentamiento = idTipoAsentamiento;
	}

}


