package mx.gob.atdt.interprete.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatEstatusSolicitud generated by hbm2java
 */
@Entity
@Table(name = "cat_estatus_solicitud", schema = "motor_interprete")
public class CatEstatusSolicitud implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idEstatusSolicitud;
	private String descripcion;

	public CatEstatusSolicitud() {
		
	}

	public CatEstatusSolicitud(Integer idEstatusSolicitud, String descripcion) {
		this.idEstatusSolicitud = idEstatusSolicitud;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id_estatus_solicitud", unique = true, nullable = false)
	public Integer getIdEstatusSolicitud() {
		return this.idEstatusSolicitud;
	}

	public void setIdEstatusSolicitud(Integer idEstatusSolicitud) {
		this.idEstatusSolicitud = idEstatusSolicitud;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
