package mx.gob.atdt.interprete.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * ComponenteDatosPersonaMoral generated by hbm2java
 */
@Entity
@Table(name = "componente_datos_persona_moral", schema = "motor_interprete")
@NamedQueries({
	@NamedQuery(name = "ComponenteDatosPersonaMoral.findByIdComponente", 
			query = "SELECT new mx.gob.atdt.interprete.dto.ComponenteDatosPersonaMoralDTO(" +
			" cdpm.idComponenteDatosPersonaMoral, c.idComponente, ctc.idTipoComponente, csf.idSubseccionFormulario," +
			" c.orden, c.requerido, c.tooltip, c.descripcionTooltip, c.tituloCampo, c.activo, c.fechaCreacion, c.fechaUltimaActualizacion, c.seccionSincronizada," +
			" cdpm.habilitaRfc, cdpm.habilitaPersonaMoral, cdpm.habilitaFechaVigencia)" +
			" FROM ComponenteDatosPersonaMoral cdpm" +
			" JOIN cdpm.componente c" +
			" JOIN c.catTipoComponente ctc" +
			" JOIN c.subseccionesFormulario csf" +
			" WHERE c.idComponente = :idComponente")
})
public class ComponenteDatosPersonaMoral implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6960667633343518436L;
	
	private Long idComponenteDatosPersonaMoral;
	private Componente componente;
	private boolean habilitaRfc;
	private boolean habilitaPersonaMoral;
	private boolean habilitaFechaVigencia;

	public ComponenteDatosPersonaMoral() {
	}

	public ComponenteDatosPersonaMoral(Long idComponenteDatosPersonaMoral, Componente componente, boolean habilitaRfc,
			boolean habilitaPersonaMoral, boolean habilitaFechaVigencia) {
		this.idComponenteDatosPersonaMoral = idComponenteDatosPersonaMoral;
		this.componente = componente;
		this.habilitaRfc = habilitaRfc;
		this.habilitaPersonaMoral = habilitaPersonaMoral;
		this.habilitaFechaVigencia = habilitaFechaVigencia;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_componente_datos_persona_moral", unique = true, nullable = false)
	public Long getIdComponenteDatosPersonaMoral() {
		return this.idComponenteDatosPersonaMoral;
	}

	public void setIdComponenteDatosPersonaMoral(Long idComponenteDatosPersonaMoral) {
		this.idComponenteDatosPersonaMoral = idComponenteDatosPersonaMoral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_componente", nullable = false)
	public Componente getComponente() {
		return this.componente;
	}

	public void setComponente(Componente componente) {
		this.componente = componente;
	}

	@Column(name = "habilita_rfc", nullable = false)
	public boolean isHabilitaRfc() {
		return this.habilitaRfc;
	}

	public void setHabilitaRfc(boolean habilitaRfc) {
		this.habilitaRfc = habilitaRfc;
	}

	@Column(name = "habilita_persona_moral", nullable = false)
	public boolean isHabilitaPersonaMoral() {
		return this.habilitaPersonaMoral;
	}

	public void setHabilitaPersonaMoral(boolean habilitaPersonaMoral) {
		this.habilitaPersonaMoral = habilitaPersonaMoral;
	}

	@Column(name = "habilita_fecha_vigencia", nullable = false)
	public boolean isHabilitaFechaVigencia() {
		return this.habilitaFechaVigencia;
	}

	public void setHabilitaFechaVigencia(boolean habilitaFechaVigencia) {
		this.habilitaFechaVigencia = habilitaFechaVigencia;
	}

}
