package mx.gob.atdt.interprete.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudLineaCaptura generated by hbm2java
 */
@Entity
@Table(name = "solicitud_linea_captura", schema = "motor_interprete")
@NamedQueries({
	@NamedQuery(name = "SolicitudLineaCaptura.findSolicitudLineaCapturaOrderByIdDesc", 
		query = "SELECT new mx.gob.atdt.interprete.dto.sat.dto.SolicitudLineaCapturaDTO("
				+ "    slc.idSolicitudLineaCaptura,"
				+ "    slc.catEstatusSolicitud.idEstatusSolicitud,"
				+ "    slc.tramites.idTramite,"
				+ "    slc.solicitudLineaCaptura,"
				+ "    slc.requestServicioLc,"
				+ "    slc.respuestaServicioLc,"
				+ "    slc.fechaCreacion"
				+ ") "
				+ "FROM SolicitudLineaCaptura slc "
				+ "WHERE slc.tramites.idTramite = :idTramite "
				+ "ORDER BY slc.idSolicitudLineaCaptura DESC")
})
public class SolicitudLineaCaptura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idSolicitudLineaCaptura;
	private CatEstatusSolicitud catEstatusSolicitud;
	private Tramites tramites;
	private String solicitudLineaCaptura;
	private String requestServicioLc;
	private String respuestaServicioLc;
	private Date fechaCreacion;

	public SolicitudLineaCaptura() {
	}

	public SolicitudLineaCaptura(long idSolicitudLineaCaptura, CatEstatusSolicitud catEstatusSolicitud,
			Tramites tramites, String requestServicioLc, String respuestaServicioLc, Date fechaCreacion) {
		this.idSolicitudLineaCaptura = idSolicitudLineaCaptura;
		this.catEstatusSolicitud = catEstatusSolicitud;
		this.tramites = tramites;
		this.requestServicioLc = requestServicioLc;
		this.respuestaServicioLc = respuestaServicioLc;
		this.fechaCreacion = fechaCreacion;
	}

	public SolicitudLineaCaptura(long idSolicitudLineaCaptura, CatEstatusSolicitud catEstatusSolicitud,
			Tramites tramites, String solicitudLineaCaptura, String requestServicioLc, String respuestaServicioLc,
			Date fechaCreacion) {
		this.idSolicitudLineaCaptura = idSolicitudLineaCaptura;
		this.catEstatusSolicitud = catEstatusSolicitud;
		this.tramites = tramites;
		this.solicitudLineaCaptura = solicitudLineaCaptura;
		this.requestServicioLc = requestServicioLc;
		this.respuestaServicioLc = respuestaServicioLc;
		this.fechaCreacion = fechaCreacion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_solicitud_linea_captura", unique = true, nullable = false)
	public long getIdSolicitudLineaCaptura() {
		return this.idSolicitudLineaCaptura;
	}

	public void setIdSolicitudLineaCaptura(long idSolicitudLineaCaptura) {
		this.idSolicitudLineaCaptura = idSolicitudLineaCaptura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_solicitud", nullable = false)
	public CatEstatusSolicitud getCatEstatusSolicitud() {
		return this.catEstatusSolicitud;
	}

	public void setCatEstatusSolicitud(CatEstatusSolicitud catEstatusSolicitud) {
		this.catEstatusSolicitud = catEstatusSolicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tramite", nullable = false)
	public Tramites getTramites() {
		return this.tramites;
	}

	public void setTramites(Tramites tramites) {
		this.tramites = tramites;
	}

	@Column(name = "solicitud_linea_captura", length = 18)
	public String getSolicitudLineaCaptura() {
		return this.solicitudLineaCaptura;
	}

	public void setSolicitudLineaCaptura(String solicitudLineaCaptura) {
		this.solicitudLineaCaptura = solicitudLineaCaptura;
	}

	@Column(name = "request_servicio_lc", nullable = false)
	public String getRequestServicioLc() {
		return this.requestServicioLc;
	}

	public void setRequestServicioLc(String requestServicioLc) {
		this.requestServicioLc = requestServicioLc;
	}

	@Column(name = "respuesta_servicio_lc", nullable = false)
	public String getRespuestaServicioLc() {
		return this.respuestaServicioLc;
	}

	public void setRespuestaServicioLc(String respuestaServicioLc) {
		this.respuestaServicioLc = respuestaServicioLc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

}
